transport.tls.enable = true
serverAddr = "47.238.174.175"
serverPort = 61921
auth.token = "Gzh@19961998"

[[proxies]]
name = "test"
type = "tcp"
localIP = "127.0.0.1"
localPort = 8080
remotePort = 61802

